### ISSUE TITLE
Opening for the public?

### ISSUE THREAD

**Issue by sauliuni** [tidal-engineering/passport-tidal#6]
Any ideas/timeframe then you give the users the opportunity to use this or an API? I would like to create automatic playlists for myself and maybe public that reuse existing public sources, like DJ streams, etc. Spotify allows that, and it's very convenient. But I would rather move to tidal for now, due to its Hi-Fi streams

**Comment by nick-fytros** [comment]
Hello @sauliuni .
There are no current plans on giving public access to users to be able to create oauth credentials.
This is mostly exposed for official TIDAL partners that might want to use it.
